/*
 * sistema-api
 * Api para o Sistema de Gerenciamento de Entregas
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.34
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The ContratacoesCandidatoBody model module.
 * @module model/ContratacoesCandidatoBody
 * @version 1.0.0
 */
export class ContratacoesCandidatoBody {
  /**
   * Constructs a new <code>ContratacoesCandidatoBody</code>.
   * @alias module:model/ContratacoesCandidatoBody
   * @class
   * @param nomePai {String} 
   * @param nomeMae {String} 
   * @param dtNasc {String} 
   * @param estadoNasc {String} 
   * @param cidadeNasc {String} 
   * @param nCpf {String} 
   * @param nCtps {String} 
   * @param dtCtps {String} 
   * @param nRg {String} 
   * @param dtRg {String} 
   * @param emitenteRg {String} 
   * @param nRua {String} 
   * @param estado {String} 
   * @param cidade {String} 
   * @param bairro {String} 
   */
  constructor(nomePai, nomeMae, dtNasc, estadoNasc, cidadeNasc, nCpf, nCtps, dtCtps, nRg, dtRg, emitenteRg, nRua, estado, cidade, bairro) {
    this.nomePai = nomePai;
    this.nomeMae = nomeMae;
    this.dtNasc = dtNasc;
    this.estadoNasc = estadoNasc;
    this.cidadeNasc = cidadeNasc;
    this.nCpf = nCpf;
    this.nCtps = nCtps;
    this.dtCtps = dtCtps;
    this.nRg = nRg;
    this.dtRg = dtRg;
    this.emitenteRg = emitenteRg;
    this.nRua = nRua;
    this.estado = estado;
    this.cidade = cidade;
    this.bairro = bairro;
  }

  /**
   * Constructs a <code>ContratacoesCandidatoBody</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ContratacoesCandidatoBody} obj Optional instance to populate.
   * @return {module:model/ContratacoesCandidatoBody} The populated <code>ContratacoesCandidatoBody</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new ContratacoesCandidatoBody();
      if (data.hasOwnProperty('nome_pai'))
        obj.nomePai = ApiClient.convertToType(data['nome_pai'], 'String');
      if (data.hasOwnProperty('nome_mae'))
        obj.nomeMae = ApiClient.convertToType(data['nome_mae'], 'String');
      if (data.hasOwnProperty('dt_nasc'))
        obj.dtNasc = ApiClient.convertToType(data['dt_nasc'], 'String');
      if (data.hasOwnProperty('estado_nasc'))
        obj.estadoNasc = ApiClient.convertToType(data['estado_nasc'], 'String');
      if (data.hasOwnProperty('cidade_nasc'))
        obj.cidadeNasc = ApiClient.convertToType(data['cidade_nasc'], 'String');
      if (data.hasOwnProperty('n_cpf'))
        obj.nCpf = ApiClient.convertToType(data['n_cpf'], 'String');
      if (data.hasOwnProperty('n_ctps'))
        obj.nCtps = ApiClient.convertToType(data['n_ctps'], 'String');
      if (data.hasOwnProperty('dt_ctps'))
        obj.dtCtps = ApiClient.convertToType(data['dt_ctps'], 'String');
      if (data.hasOwnProperty('n_rg'))
        obj.nRg = ApiClient.convertToType(data['n_rg'], 'String');
      if (data.hasOwnProperty('dt_rg'))
        obj.dtRg = ApiClient.convertToType(data['dt_rg'], 'String');
      if (data.hasOwnProperty('emitente_rg'))
        obj.emitenteRg = ApiClient.convertToType(data['emitente_rg'], 'String');
      if (data.hasOwnProperty('n_rua'))
        obj.nRua = ApiClient.convertToType(data['n_rua'], 'String');
      if (data.hasOwnProperty('estado'))
        obj.estado = ApiClient.convertToType(data['estado'], 'String');
      if (data.hasOwnProperty('cidade'))
        obj.cidade = ApiClient.convertToType(data['cidade'], 'String');
      if (data.hasOwnProperty('bairro'))
        obj.bairro = ApiClient.convertToType(data['bairro'], 'String');
    }
    return obj;
  }
}

/**
 * @member {String} nomePai
 */
ContratacoesCandidatoBody.prototype.nomePai = undefined;

/**
 * @member {String} nomeMae
 */
ContratacoesCandidatoBody.prototype.nomeMae = undefined;

/**
 * @member {String} dtNasc
 */
ContratacoesCandidatoBody.prototype.dtNasc = undefined;

/**
 * @member {String} estadoNasc
 */
ContratacoesCandidatoBody.prototype.estadoNasc = undefined;

/**
 * @member {String} cidadeNasc
 */
ContratacoesCandidatoBody.prototype.cidadeNasc = undefined;

/**
 * @member {String} nCpf
 */
ContratacoesCandidatoBody.prototype.nCpf = undefined;

/**
 * @member {String} nCtps
 */
ContratacoesCandidatoBody.prototype.nCtps = undefined;

/**
 * @member {String} dtCtps
 */
ContratacoesCandidatoBody.prototype.dtCtps = undefined;

/**
 * @member {String} nRg
 */
ContratacoesCandidatoBody.prototype.nRg = undefined;

/**
 * @member {String} dtRg
 */
ContratacoesCandidatoBody.prototype.dtRg = undefined;

/**
 * @member {String} emitenteRg
 */
ContratacoesCandidatoBody.prototype.emitenteRg = undefined;

/**
 * @member {String} nRua
 */
ContratacoesCandidatoBody.prototype.nRua = undefined;

/**
 * @member {String} estado
 */
ContratacoesCandidatoBody.prototype.estado = undefined;

/**
 * @member {String} cidade
 */
ContratacoesCandidatoBody.prototype.cidade = undefined;

/**
 * @member {String} bairro
 */
ContratacoesCandidatoBody.prototype.bairro = undefined;

