/*
 * sistema-api
 * Api para o Sistema de Gerenciamento de Entregas
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.34
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The InlineResponse2003 model module.
 * @module model/InlineResponse2003
 * @version 1.0.0
 */
export class InlineResponse2003 {
  /**
   * Constructs a new <code>InlineResponse2003</code>.
   * @alias module:model/InlineResponse2003
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>InlineResponse2003</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/InlineResponse2003} obj Optional instance to populate.
   * @return {module:model/InlineResponse2003} The populated <code>InlineResponse2003</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new InlineResponse2003();
      if (data.hasOwnProperty('cdempresa'))
        obj.cdempresa = ApiClient.convertToType(data['cdempresa'], 'Number');
      if (data.hasOwnProperty('nmempresa'))
        obj.nmempresa = ApiClient.convertToType(data['nmempresa'], 'String');
    }
    return obj;
  }
}

/**
 * @member {Number} cdempresa
 */
InlineResponse2003.prototype.cdempresa = undefined;

/**
 * Allowed values for the <code>nmempresa</code> property.
 * @enum {String}
 * @readonly
 */
InlineResponse2003.NmempresaEnum = {
  /**
   * value: "Nome da Empresa"
   * @const
   */
  nomeDaEmpresa: "Nome da Empresa"
};
/**
 * @member {module:model/InlineResponse2003.NmempresaEnum} nmempresa
 */
InlineResponse2003.prototype.nmempresa = undefined;

