/*
 * sistema-api
 * Api para o Sistema de Gerenciamento de Entregas
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.34
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The InlineResponse2013 model module.
 * @module model/InlineResponse2013
 * @version 1.0.0
 */
export class InlineResponse2013 {
  /**
   * Constructs a new <code>InlineResponse2013</code>.
   * @alias module:model/InlineResponse2013
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>InlineResponse2013</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/InlineResponse2013} obj Optional instance to populate.
   * @return {module:model/InlineResponse2013} The populated <code>InlineResponse2013</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new InlineResponse2013();
      if (data.hasOwnProperty('cbo_id'))
        obj.cboId = ApiClient.convertToType(data['cbo_id'], 'String');
      if (data.hasOwnProperty('ocupacao'))
        obj.ocupacao = ApiClient.convertToType(data['ocupacao'], 'String');
      if (data.hasOwnProperty('grande_grupo'))
        obj.grandeGrupo = ApiClient.convertToType(data['grande_grupo'], 'String');
      if (data.hasOwnProperty('subgrupo_principal'))
        obj.subgrupoPrincipal = ApiClient.convertToType(data['subgrupo_principal'], 'String');
      if (data.hasOwnProperty('subgrupo'))
        obj.subgrupo = ApiClient.convertToType(data['subgrupo'], 'String');
      if (data.hasOwnProperty('familia'))
        obj.familia = ApiClient.convertToType(data['familia'], 'String');
    }
    return obj;
  }
}

/**
 * Allowed values for the <code>cboId</code> property.
 * @enum {String}
 * @readonly
 */
InlineResponse2013.CboIdEnum = {
  /**
   * value: "sucesso"
   * @const
   */
  sucesso: "sucesso"
};
/**
 * @member {module:model/InlineResponse2013.CboIdEnum} cboId
 */
InlineResponse2013.prototype.cboId = undefined;

/**
 * @member {String} ocupacao
 */
InlineResponse2013.prototype.ocupacao = undefined;

/**
 * @member {String} grandeGrupo
 */
InlineResponse2013.prototype.grandeGrupo = undefined;

/**
 * @member {String} subgrupoPrincipal
 */
InlineResponse2013.prototype.subgrupoPrincipal = undefined;

/**
 * @member {String} subgrupo
 */
InlineResponse2013.prototype.subgrupo = undefined;

/**
 * @member {String} familia
 */
InlineResponse2013.prototype.familia = undefined;

