/*
 * sistema-api
 * Api para o Sistema de Gerenciamento de Entregas
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.34
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The InlineResponse2011 model module.
 * @module model/InlineResponse2011
 * @version 1.0.0
 */
export class InlineResponse2011 {
  /**
   * Constructs a new <code>InlineResponse2011</code>.
   * @alias module:model/InlineResponse2011
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>InlineResponse2011</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/InlineResponse2011} obj Optional instance to populate.
   * @return {module:model/InlineResponse2011} The populated <code>InlineResponse2011</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new InlineResponse2011();
      if (data.hasOwnProperty('contratacao_id'))
        obj.contratacaoId = ApiClient.convertToType(data['contratacao_id'], 'String');
      if (data.hasOwnProperty('nome_pai'))
        obj.nomePai = ApiClient.convertToType(data['nome_pai'], 'String');
      if (data.hasOwnProperty('nome_mae'))
        obj.nomeMae = ApiClient.convertToType(data['nome_mae'], 'String');
      if (data.hasOwnProperty('dt_nasc'))
        obj.dtNasc = ApiClient.convertToType(data['dt_nasc'], 'String');
      if (data.hasOwnProperty('estado_nasc'))
        obj.estadoNasc = ApiClient.convertToType(data['estado_nasc'], 'String');
      if (data.hasOwnProperty('cidade_nasc'))
        obj.cidadeNasc = ApiClient.convertToType(data['cidade_nasc'], 'String');
      if (data.hasOwnProperty('n_cpf'))
        obj.nCpf = ApiClient.convertToType(data['n_cpf'], 'String');
      if (data.hasOwnProperty('n_ctps'))
        obj.nCtps = ApiClient.convertToType(data['n_ctps'], 'String');
      if (data.hasOwnProperty('dt_ctps'))
        obj.dtCtps = ApiClient.convertToType(data['dt_ctps'], 'String');
      if (data.hasOwnProperty('n_rg'))
        obj.nRg = ApiClient.convertToType(data['n_rg'], 'String');
      if (data.hasOwnProperty('dt_rg'))
        obj.dtRg = ApiClient.convertToType(data['dt_rg'], 'String');
      if (data.hasOwnProperty('emitente_rg'))
        obj.emitenteRg = ApiClient.convertToType(data['emitente_rg'], 'String');
      if (data.hasOwnProperty('n_rua'))
        obj.nRua = ApiClient.convertToType(data['n_rua'], 'String');
      if (data.hasOwnProperty('estado'))
        obj.estado = ApiClient.convertToType(data['estado'], 'String');
      if (data.hasOwnProperty('cidade'))
        obj.cidade = ApiClient.convertToType(data['cidade'], 'String');
      if (data.hasOwnProperty('bairro'))
        obj.bairro = ApiClient.convertToType(data['bairro'], 'String');
    }
    return obj;
  }
}

/**
 * @member {String} contratacaoId
 */
InlineResponse2011.prototype.contratacaoId = undefined;

/**
 * @member {String} nomePai
 */
InlineResponse2011.prototype.nomePai = undefined;

/**
 * @member {String} nomeMae
 */
InlineResponse2011.prototype.nomeMae = undefined;

/**
 * @member {String} dtNasc
 */
InlineResponse2011.prototype.dtNasc = undefined;

/**
 * @member {String} estadoNasc
 */
InlineResponse2011.prototype.estadoNasc = undefined;

/**
 * @member {String} cidadeNasc
 */
InlineResponse2011.prototype.cidadeNasc = undefined;

/**
 * @member {String} nCpf
 */
InlineResponse2011.prototype.nCpf = undefined;

/**
 * @member {String} nCtps
 */
InlineResponse2011.prototype.nCtps = undefined;

/**
 * @member {String} dtCtps
 */
InlineResponse2011.prototype.dtCtps = undefined;

/**
 * @member {String} nRg
 */
InlineResponse2011.prototype.nRg = undefined;

/**
 * @member {String} dtRg
 */
InlineResponse2011.prototype.dtRg = undefined;

/**
 * @member {String} emitenteRg
 */
InlineResponse2011.prototype.emitenteRg = undefined;

/**
 * @member {String} nRua
 */
InlineResponse2011.prototype.nRua = undefined;

/**
 * @member {String} estado
 */
InlineResponse2011.prototype.estado = undefined;

/**
 * @member {String} cidade
 */
InlineResponse2011.prototype.cidade = undefined;

/**
 * @member {String} bairro
 */
InlineResponse2011.prototype.bairro = undefined;

