/*
 * sistema-api
 * Api para o Sistema de Gerenciamento de Entregas
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.34
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The V1HorariosBody model module.
 * @module model/V1HorariosBody
 * @version 1.0.0
 */
export class V1HorariosBody {
  /**
   * Constructs a new <code>V1HorariosBody</code>.
   * @alias module:model/V1HorariosBody
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>V1HorariosBody</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/V1HorariosBody} obj Optional instance to populate.
   * @return {module:model/V1HorariosBody} The populated <code>V1HorariosBody</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new V1HorariosBody();
      if (data.hasOwnProperty('descricao'))
        obj.descricao = ApiClient.convertToType(data['descricao'], 'String');
      if (data.hasOwnProperty('dom_entrada'))
        obj.domEntrada = ApiClient.convertToType(data['dom_entrada'], 'String');
      if (data.hasOwnProperty('dom_almoco_saida'))
        obj.domAlmocoSaida = ApiClient.convertToType(data['dom_almoco_saida'], 'String');
      if (data.hasOwnProperty('dom_amoco_retorno'))
        obj.domAmocoRetorno = ApiClient.convertToType(data['dom_amoco_retorno'], 'String');
      if (data.hasOwnProperty('dom_saida'))
        obj.domSaida = ApiClient.convertToType(data['dom_saida'], 'String');
      if (data.hasOwnProperty('dom_intervalo'))
        obj.domIntervalo = ApiClient.convertToType(data['dom_intervalo'], 'String');
      if (data.hasOwnProperty('seg_entrada'))
        obj.segEntrada = ApiClient.convertToType(data['seg_entrada'], 'String');
      if (data.hasOwnProperty('seg_almoco_saida'))
        obj.segAlmocoSaida = ApiClient.convertToType(data['seg_almoco_saida'], 'String');
      if (data.hasOwnProperty('seg_amoco_retorno'))
        obj.segAmocoRetorno = ApiClient.convertToType(data['seg_amoco_retorno'], 'String');
      if (data.hasOwnProperty('seg_saida'))
        obj.segSaida = ApiClient.convertToType(data['seg_saida'], 'String');
      if (data.hasOwnProperty('seg_intervalo'))
        obj.segIntervalo = ApiClient.convertToType(data['seg_intervalo'], 'String');
      if (data.hasOwnProperty('ter_entrada'))
        obj.terEntrada = ApiClient.convertToType(data['ter_entrada'], 'String');
      if (data.hasOwnProperty('ter_almoco_saida'))
        obj.terAlmocoSaida = ApiClient.convertToType(data['ter_almoco_saida'], 'String');
      if (data.hasOwnProperty('ter_amoco_retorno'))
        obj.terAmocoRetorno = ApiClient.convertToType(data['ter_amoco_retorno'], 'String');
      if (data.hasOwnProperty('ter_saida'))
        obj.terSaida = ApiClient.convertToType(data['ter_saida'], 'String');
      if (data.hasOwnProperty('ter_intervalo'))
        obj.terIntervalo = ApiClient.convertToType(data['ter_intervalo'], 'String');
      if (data.hasOwnProperty('quar_entrada'))
        obj.quarEntrada = ApiClient.convertToType(data['quar_entrada'], 'String');
      if (data.hasOwnProperty('quar_almoco_saida'))
        obj.quarAlmocoSaida = ApiClient.convertToType(data['quar_almoco_saida'], 'String');
      if (data.hasOwnProperty('quar_amoco_retorno'))
        obj.quarAmocoRetorno = ApiClient.convertToType(data['quar_amoco_retorno'], 'String');
      if (data.hasOwnProperty('quar_saida'))
        obj.quarSaida = ApiClient.convertToType(data['quar_saida'], 'String');
      if (data.hasOwnProperty('quar_intervalo'))
        obj.quarIntervalo = ApiClient.convertToType(data['quar_intervalo'], 'String');
      if (data.hasOwnProperty('quin_entrada'))
        obj.quinEntrada = ApiClient.convertToType(data['quin_entrada'], 'String');
      if (data.hasOwnProperty('quin_almoco_saida'))
        obj.quinAlmocoSaida = ApiClient.convertToType(data['quin_almoco_saida'], 'String');
      if (data.hasOwnProperty('quin_amoco_retorno'))
        obj.quinAmocoRetorno = ApiClient.convertToType(data['quin_amoco_retorno'], 'String');
      if (data.hasOwnProperty('quin_saida'))
        obj.quinSaida = ApiClient.convertToType(data['quin_saida'], 'String');
      if (data.hasOwnProperty('quin_intervalo'))
        obj.quinIntervalo = ApiClient.convertToType(data['quin_intervalo'], 'String');
      if (data.hasOwnProperty('sex_entrada'))
        obj.sexEntrada = ApiClient.convertToType(data['sex_entrada'], 'String');
      if (data.hasOwnProperty('sex_almoco_saida'))
        obj.sexAlmocoSaida = ApiClient.convertToType(data['sex_almoco_saida'], 'String');
      if (data.hasOwnProperty('sex_amoco_retorno'))
        obj.sexAmocoRetorno = ApiClient.convertToType(data['sex_amoco_retorno'], 'String');
      if (data.hasOwnProperty('sex_saida'))
        obj.sexSaida = ApiClient.convertToType(data['sex_saida'], 'String');
      if (data.hasOwnProperty('sex_intervalo'))
        obj.sexIntervalo = ApiClient.convertToType(data['sex_intervalo'], 'String');
      if (data.hasOwnProperty('sab_entrada'))
        obj.sabEntrada = ApiClient.convertToType(data['sab_entrada'], 'String');
      if (data.hasOwnProperty('sab_almoco_saida'))
        obj.sabAlmocoSaida = ApiClient.convertToType(data['sab_almoco_saida'], 'String');
      if (data.hasOwnProperty('sab_amoco_retorno'))
        obj.sabAmocoRetorno = ApiClient.convertToType(data['sab_amoco_retorno'], 'String');
      if (data.hasOwnProperty('sab_saida'))
        obj.sabSaida = ApiClient.convertToType(data['sab_saida'], 'String');
      if (data.hasOwnProperty('sab_intervalo'))
        obj.sabIntervalo = ApiClient.convertToType(data['sab_intervalo'], 'String');
    }
    return obj;
  }
}

/**
 * @member {String} descricao
 */
V1HorariosBody.prototype.descricao = undefined;

/**
 * @member {String} domEntrada
 */
V1HorariosBody.prototype.domEntrada = undefined;

/**
 * @member {String} domAlmocoSaida
 */
V1HorariosBody.prototype.domAlmocoSaida = undefined;

/**
 * @member {String} domAmocoRetorno
 */
V1HorariosBody.prototype.domAmocoRetorno = undefined;

/**
 * @member {String} domSaida
 */
V1HorariosBody.prototype.domSaida = undefined;

/**
 * @member {String} domIntervalo
 */
V1HorariosBody.prototype.domIntervalo = undefined;

/**
 * @member {String} segEntrada
 */
V1HorariosBody.prototype.segEntrada = undefined;

/**
 * @member {String} segAlmocoSaida
 */
V1HorariosBody.prototype.segAlmocoSaida = undefined;

/**
 * @member {String} segAmocoRetorno
 */
V1HorariosBody.prototype.segAmocoRetorno = undefined;

/**
 * @member {String} segSaida
 */
V1HorariosBody.prototype.segSaida = undefined;

/**
 * @member {String} segIntervalo
 */
V1HorariosBody.prototype.segIntervalo = undefined;

/**
 * @member {String} terEntrada
 */
V1HorariosBody.prototype.terEntrada = undefined;

/**
 * @member {String} terAlmocoSaida
 */
V1HorariosBody.prototype.terAlmocoSaida = undefined;

/**
 * @member {String} terAmocoRetorno
 */
V1HorariosBody.prototype.terAmocoRetorno = undefined;

/**
 * @member {String} terSaida
 */
V1HorariosBody.prototype.terSaida = undefined;

/**
 * @member {String} terIntervalo
 */
V1HorariosBody.prototype.terIntervalo = undefined;

/**
 * @member {String} quarEntrada
 */
V1HorariosBody.prototype.quarEntrada = undefined;

/**
 * @member {String} quarAlmocoSaida
 */
V1HorariosBody.prototype.quarAlmocoSaida = undefined;

/**
 * @member {String} quarAmocoRetorno
 */
V1HorariosBody.prototype.quarAmocoRetorno = undefined;

/**
 * @member {String} quarSaida
 */
V1HorariosBody.prototype.quarSaida = undefined;

/**
 * @member {String} quarIntervalo
 */
V1HorariosBody.prototype.quarIntervalo = undefined;

/**
 * @member {String} quinEntrada
 */
V1HorariosBody.prototype.quinEntrada = undefined;

/**
 * @member {String} quinAlmocoSaida
 */
V1HorariosBody.prototype.quinAlmocoSaida = undefined;

/**
 * @member {String} quinAmocoRetorno
 */
V1HorariosBody.prototype.quinAmocoRetorno = undefined;

/**
 * @member {String} quinSaida
 */
V1HorariosBody.prototype.quinSaida = undefined;

/**
 * @member {String} quinIntervalo
 */
V1HorariosBody.prototype.quinIntervalo = undefined;

/**
 * @member {String} sexEntrada
 */
V1HorariosBody.prototype.sexEntrada = undefined;

/**
 * @member {String} sexAlmocoSaida
 */
V1HorariosBody.prototype.sexAlmocoSaida = undefined;

/**
 * @member {String} sexAmocoRetorno
 */
V1HorariosBody.prototype.sexAmocoRetorno = undefined;

/**
 * @member {String} sexSaida
 */
V1HorariosBody.prototype.sexSaida = undefined;

/**
 * @member {String} sexIntervalo
 */
V1HorariosBody.prototype.sexIntervalo = undefined;

/**
 * @member {String} sabEntrada
 */
V1HorariosBody.prototype.sabEntrada = undefined;

/**
 * @member {String} sabAlmocoSaida
 */
V1HorariosBody.prototype.sabAlmocoSaida = undefined;

/**
 * @member {String} sabAmocoRetorno
 */
V1HorariosBody.prototype.sabAmocoRetorno = undefined;

/**
 * @member {String} sabSaida
 */
V1HorariosBody.prototype.sabSaida = undefined;

/**
 * @member {String} sabIntervalo
 */
V1HorariosBody.prototype.sabIntervalo = undefined;

