/*
 * sistema-api
 * Api para o Sistema de Gerenciamento de Entregas
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.34
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The V1UsuarioBody1 model module.
 * @module model/V1UsuarioBody1
 * @version 1.0.0
 */
export class V1UsuarioBody1 {
  /**
   * Constructs a new <code>V1UsuarioBody1</code>.
   * @alias module:model/V1UsuarioBody1
   * @class
   * @param email {String} 
   * @param nome {Number} 
   * @param tipo {Number} 
   */
  constructor(email, nome, tipo) {
    this.email = email;
    this.nome = nome;
    this.tipo = tipo;
  }

  /**
   * Constructs a <code>V1UsuarioBody1</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/V1UsuarioBody1} obj Optional instance to populate.
   * @return {module:model/V1UsuarioBody1} The populated <code>V1UsuarioBody1</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new V1UsuarioBody1();
      if (data.hasOwnProperty('email'))
        obj.email = ApiClient.convertToType(data['email'], 'String');
      if (data.hasOwnProperty('telefone'))
        obj.telefone = ApiClient.convertToType(data['telefone'], 'Number');
      if (data.hasOwnProperty('whatsapp'))
        obj.whatsapp = ApiClient.convertToType(data['whatsapp'], 'Boolean');
      if (data.hasOwnProperty('oauthgoogle'))
        obj.oauthgoogle = ApiClient.convertToType(data['oauthgoogle'], 'String');
      if (data.hasOwnProperty('oauthhotmail'))
        obj.oauthhotmail = ApiClient.convertToType(data['oauthhotmail'], 'String');
      if (data.hasOwnProperty('nome'))
        obj.nome = ApiClient.convertToType(data['nome'], 'Number');
      if (data.hasOwnProperty('tipo'))
        obj.tipo = ApiClient.convertToType(data['tipo'], 'Number');
    }
    return obj;
  }
}

/**
 * @member {String} email
 */
V1UsuarioBody1.prototype.email = undefined;

/**
 * @member {Number} telefone
 */
V1UsuarioBody1.prototype.telefone = undefined;

/**
 * @member {Boolean} whatsapp
 */
V1UsuarioBody1.prototype.whatsapp = undefined;

/**
 * @member {String} oauthgoogle
 */
V1UsuarioBody1.prototype.oauthgoogle = undefined;

/**
 * @member {String} oauthhotmail
 */
V1UsuarioBody1.prototype.oauthhotmail = undefined;

/**
 * @member {Number} nome
 */
V1UsuarioBody1.prototype.nome = undefined;

/**
 * @member {Number} tipo
 */
V1UsuarioBody1.prototype.tipo = undefined;

