/*
 * sistema-api
 * Api para o Sistema de Gerenciamento de Entregas
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.34
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The V1UsuarioBody model module.
 * @module model/V1UsuarioBody
 * @version 1.0.0
 */
export class V1UsuarioBody {
  /**
   * Constructs a new <code>V1UsuarioBody</code>.
   * @alias module:model/V1UsuarioBody
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>V1UsuarioBody</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/V1UsuarioBody} obj Optional instance to populate.
   * @return {module:model/V1UsuarioBody} The populated <code>V1UsuarioBody</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new V1UsuarioBody();
      if (data.hasOwnProperty('user_id'))
        obj.userId = ApiClient.convertToType(data['user_id'], 'Number');
      if (data.hasOwnProperty('nome'))
        obj.nome = ApiClient.convertToType(data['nome'], 'String');
    }
    return obj;
  }
}

/**
 * @member {Number} userId
 */
V1UsuarioBody.prototype.userId = undefined;

/**
 * Allowed values for the <code>nome</code> property.
 * @enum {String}
 * @readonly
 */
V1UsuarioBody.NomeEnum = {
  /**
   * value: "Nome do Usuário"
   * @const
   */
  nomeDoUsurio: "Nome do Usuário"
};
/**
 * @member {module:model/V1UsuarioBody.NomeEnum} nome
 */
V1UsuarioBody.prototype.nome = undefined;

