/*
 * sistema-api
 * Api para o Sistema de Gerenciamento de Entregas
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.34
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from "../ApiClient";

/**
* Funcionrios service.
* @module api/FuncionriosApi
* @version 1.0.0
*/
export class FuncionriosApi {

    /**
    * Constructs a new FuncionriosApi. 
    * @alias module:api/FuncionriosApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instanc
    e} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }

    /**
     * Callback function to receive the result of the getFuncionarios operation.
     * @callback moduleapi/FuncionriosApi~getFuncionariosCallback
     * @param {String} error Error message, if any.
     * @param {Array.<'String'>{ data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * retorna a lista de todos os funcionarios da empresa
     * @param {Number} empresaId 
     * @param {module:api/FuncionriosApi~getFuncionariosCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link <&vendorExtensions.x-jsdoc-type>}
     */
    getFuncionarios(empresaId, callback) {
      
      let postBody = null;
      // verify the required parameter 'empresaId' is set
      if (empresaId === undefined || empresaId === null) {
        throw new Error("Missing the required parameter 'empresaId' when calling getFuncionarios");
      }

      let pathParams = {
        
      };
      let queryParams = {
        'empresaId': empresaId
      };
      let headerParams = {
        
      };
      let formParams = {
        
      };

      let authNames = ['bearerAuth'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = ['String'];

      return this.apiClient.callApi(
        '/v1/funcionarios', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

}