/*
 * sistema-api
 * Api para o Sistema de Gerenciamento de Entregas
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.34
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.SistemaApi);
  }
}(this, function(expect, SistemaApi) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('InlineResponse2004', function() {
      beforeEach(function() {
        instance = new SistemaApi.InlineResponse2004();
      });

      it('should create an instance of InlineResponse2004', function() {
        // TODO: update the code to test InlineResponse2004
        expect(instance).to.be.a(SistemaApi.InlineResponse2004);
      });

      it('should have the property idfuncionario (base name: "idfuncionario")', function() {
        // TODO: update the code to test the property idfuncionario
        expect(instance).to.have.property('idfuncionario');
        // expect(instance.idfuncionario).to.be(expectedValueLiteral);
      });

      it('should have the property dtperiodoaquisinicial (base name: "dtperiodoaquisinicial")', function() {
        // TODO: update the code to test the property dtperiodoaquisinicial
        expect(instance).to.have.property('dtperiodoaquisinicial');
        // expect(instance.dtperiodoaquisinicial).to.be(expectedValueLiteral);
      });

      it('should have the property dtperiodoaquisfinal (base name: "dtperiodoaquisfinal")', function() {
        // TODO: update the code to test the property dtperiodoaquisfinal
        expect(instance).to.have.property('dtperiodoaquisfinal');
        // expect(instance.dtperiodoaquisfinal).to.be(expectedValueLiteral);
      });

    });
  });

}));
