/*
 * sistema-api
 * Api para o Sistema de Gerenciamento de Entregas
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.34
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.SistemaApi);
  }
}(this, function(expect, SistemaApi) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('InlineResponse2013', function() {
      beforeEach(function() {
        instance = new SistemaApi.InlineResponse2013();
      });

      it('should create an instance of InlineResponse2013', function() {
        // TODO: update the code to test InlineResponse2013
        expect(instance).to.be.a(SistemaApi.InlineResponse2013);
      });

      it('should have the property cboId (base name: "cbo_id")', function() {
        // TODO: update the code to test the property cboId
        expect(instance).to.have.property('cboId');
        // expect(instance.cboId).to.be(expectedValueLiteral);
      });

      it('should have the property ocupacao (base name: "ocupacao")', function() {
        // TODO: update the code to test the property ocupacao
        expect(instance).to.have.property('ocupacao');
        // expect(instance.ocupacao).to.be(expectedValueLiteral);
      });

      it('should have the property grandeGrupo (base name: "grande_grupo")', function() {
        // TODO: update the code to test the property grandeGrupo
        expect(instance).to.have.property('grandeGrupo');
        // expect(instance.grandeGrupo).to.be(expectedValueLiteral);
      });

      it('should have the property subgrupoPrincipal (base name: "subgrupo_principal")', function() {
        // TODO: update the code to test the property subgrupoPrincipal
        expect(instance).to.have.property('subgrupoPrincipal');
        // expect(instance.subgrupoPrincipal).to.be(expectedValueLiteral);
      });

      it('should have the property subgrupo (base name: "subgrupo")', function() {
        // TODO: update the code to test the property subgrupo
        expect(instance).to.have.property('subgrupo');
        // expect(instance.subgrupo).to.be(expectedValueLiteral);
      });

      it('should have the property familia (base name: "familia")', function() {
        // TODO: update the code to test the property familia
        expect(instance).to.have.property('familia');
        // expect(instance.familia).to.be(expectedValueLiteral);
      });

    });
  });

}));
