/*
 * sistema-api
 * Api para o Sistema de Gerenciamento de Entregas
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.34
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.SistemaApi);
  }
}(this, function(expect, SistemaApi) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('InlineResponse2002', function() {
      beforeEach(function() {
        instance = new SistemaApi.InlineResponse2002();
      });

      it('should create an instance of InlineResponse2002', function() {
        // TODO: update the code to test InlineResponse2002
        expect(instance).to.be.a(SistemaApi.InlineResponse2002);
      });

      it('should have the property competencia (base name: "competencia")', function() {
        // TODO: update the code to test the property competencia
        expect(instance).to.have.property('competencia');
        // expect(instance.competencia).to.be(expectedValueLiteral);
      });

      it('should have the property tipo (base name: "tipo")', function() {
        // TODO: update the code to test the property tipo
        expect(instance).to.have.property('tipo');
        // expect(instance.tipo).to.be(expectedValueLiteral);
      });

      it('should have the property nomeArq (base name: "nome_arq")', function() {
        // TODO: update the code to test the property nomeArq
        expect(instance).to.have.property('nomeArq');
        // expect(instance.nomeArq).to.be(expectedValueLiteral);
      });

    });
  });

}));
