/*
 * sistema-api
 * Api para o Sistema de Gerenciamento de Entregas
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.34
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.SistemaApi);
  }
}(this, function(expect, SistemaApi) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('InlineResponse2005', function() {
      beforeEach(function() {
        instance = new SistemaApi.InlineResponse2005();
      });

      it('should create an instance of InlineResponse2005', function() {
        // TODO: update the code to test InlineResponse2005
        expect(instance).to.be.a(SistemaApi.InlineResponse2005);
      });

      it('should have the property modId (base name: "mod_id")', function() {
        // TODO: update the code to test the property modId
        expect(instance).to.have.property('modId');
        // expect(instance.modId).to.be(expectedValueLiteral);
      });

      it('should have the property modNome (base name: "mod_nome")', function() {
        // TODO: update the code to test the property modNome
        expect(instance).to.have.property('modNome');
        // expect(instance.modNome).to.be(expectedValueLiteral);
      });

    });
  });

}));
