/*
 * sistema-api
 * Api para o Sistema de Gerenciamento de Entregas
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.34
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.SistemaApi);
  }
}(this, function(expect, SistemaApi) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('InlineResponse201', function() {
      beforeEach(function() {
        instance = new SistemaApi.InlineResponse201();
      });

      it('should create an instance of InlineResponse201', function() {
        // TODO: update the code to test InlineResponse201
        expect(instance).to.be.a(SistemaApi.InlineResponse201);
      });

      it('should have the property status (base name: "status")', function() {
        // TODO: update the code to test the property status
        expect(instance).to.have.property('status');
        // expect(instance.status).to.be(expectedValueLiteral);
      });

      it('should have the property contratacaoId (base name: "contratacao_id")', function() {
        // TODO: update the code to test the property contratacaoId
        expect(instance).to.have.property('contratacaoId');
        // expect(instance.contratacaoId).to.be(expectedValueLiteral);
      });

    });
  });

}));
