/*
 * sistema-api
 * Api para o Sistema de Gerenciamento de Entregas
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.34
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.SistemaApi);
  }
}(this, function(expect, SistemaApi) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('V1CboBody', function() {
      beforeEach(function() {
        instance = new SistemaApi.V1CboBody();
      });

      it('should create an instance of V1CboBody', function() {
        // TODO: update the code to test V1CboBody
        expect(instance).to.be.a(SistemaApi.V1CboBody);
      });

      it('should have the property cbo (base name: "cbo")', function() {
        // TODO: update the code to test the property cbo
        expect(instance).to.have.property('cbo');
        // expect(instance.cbo).to.be(expectedValueLiteral);
      });

      it('should have the property familia (base name: "familia")', function() {
        // TODO: update the code to test the property familia
        expect(instance).to.have.property('familia');
        // expect(instance.familia).to.be(expectedValueLiteral);
      });

      it('should have the property gradeGrupo (base name: "grade_grupo")', function() {
        // TODO: update the code to test the property gradeGrupo
        expect(instance).to.have.property('gradeGrupo');
        // expect(instance.gradeGrupo).to.be(expectedValueLiteral);
      });

      it('should have the property ocupacao (base name: "ocupacao")', function() {
        // TODO: update the code to test the property ocupacao
        expect(instance).to.have.property('ocupacao');
        // expect(instance.ocupacao).to.be(expectedValueLiteral);
      });

      it('should have the property perfilOcupacional (base name: "perfil_ocupacional")', function() {
        // TODO: update the code to test the property perfilOcupacional
        expect(instance).to.have.property('perfilOcupacional');
        // expect(instance.perfilOcupacional).to.be(expectedValueLiteral);
      });

      it('should have the property sinonimo (base name: "sinonimo")', function() {
        // TODO: update the code to test the property sinonimo
        expect(instance).to.have.property('sinonimo');
        // expect(instance.sinonimo).to.be(expectedValueLiteral);
      });

      it('should have the property subgrupoPricipal (base name: "subgrupo_pricipal")', function() {
        // TODO: update the code to test the property subgrupoPricipal
        expect(instance).to.have.property('subgrupoPricipal');
        // expect(instance.subgrupoPricipal).to.be(expectedValueLiteral);
      });

      it('should have the property subgrupo (base name: "subgrupo")', function() {
        // TODO: update the code to test the property subgrupo
        expect(instance).to.have.property('subgrupo');
        // expect(instance.subgrupo).to.be(expectedValueLiteral);
      });

    });
  });

}));
