/*
 * sistema-api
 * Api para o Sistema de Gerenciamento de Entregas
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.34
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.SistemaApi);
  }
}(this, function(expect, SistemaApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new SistemaApi.ContrataesApi();
  });

  describe('(package)', function() {
    describe('ContrataesApi', function() {
      describe('v1ContratacoesCandidatoGet', function() {
        it('should call v1ContratacoesCandidatoGet successfully', function(done) {
          // TODO: uncomment, update parameter values for v1ContratacoesCandidatoGet call and complete the assertions
          /*

          instance.v1ContratacoesCandidatoGet(contratacaoId, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(SistemaApi.InlineResponse2011);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('v1ContratacoesCandidatoPost', function() {
        it('should call v1ContratacoesCandidatoPost successfully', function(done) {
          // TODO: uncomment, update parameter values for v1ContratacoesCandidatoPost call and complete the assertions
          /*

          instance.v1ContratacoesCandidatoPost(nomePai, nomeMae, dtNasc, estadoNasc, cidadeNasc, nCpf, nCtps, dtCtps, nRg, dtRg, emitenteRg, nRua, estado, cidade, bairro, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(SistemaApi.InlineResponse201);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('v1ContratacoesGet', function() {
        it('should call v1ContratacoesGet successfully', function(done) {
          // TODO: uncomment, update parameter values for v1ContratacoesGet call and complete the assertions
          /*

          instance.v1ContratacoesGet(cdempresa, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(SistemaApi.InlineResponse2006);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('v1ContratacoesPatch', function() {
        it('should call v1ContratacoesPatch successfully', function(done) {
          // TODO: uncomment, update parameter values for v1ContratacoesPatch call and complete the assertions
          /*

          instance.v1ContratacoesPatch(contratacaoId, status, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(SistemaApi.InlineResponse201);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('v1ContratacoesPost', function() {
        it('should call v1ContratacoesPost successfully', function(done) {
          // TODO: uncomment, update parameter values for v1ContratacoesPost call and complete the assertions
          /*

          instance.v1ContratacoesPost(cdempresa, nome, data, funcao, cboId, horaId, salario, tipoContrato, modNome, email, telefone, whatsapp, dtContratacao, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(SistemaApi.InlineResponse2001);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
    });
  });

}));
