/*
 * sistema-api
 * Api para o Sistema de Gerenciamento de Entregas
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.34
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.SistemaApi);
  }
}(this, function(expect, SistemaApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new SistemaApi.UsurioApi();
  });

  describe('(package)', function() {
    describe('UsurioApi', function() {
      describe('getUsuario', function() {
        it('should call getUsuario successfully', function(done) {
          // TODO: uncomment, update parameter values for getUsuario call and complete the assertions
          /*
          var opts = {};

          instance.getUsuario(opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(SistemaApi.InlineResponse200);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('v1UsuarioDelete', function() {
        it('should call v1UsuarioDelete successfully', function(done) {
          // TODO: uncomment, update parameter values for v1UsuarioDelete call
          /*

          instance.v1UsuarioDelete(userId, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('v1UsuarioPost', function() {
        it('should call v1UsuarioPost successfully', function(done) {
          // TODO: uncomment, update parameter values for v1UsuarioPost call
          /*

          instance.v1UsuarioPost(email, telefone, whatsapp, oauthgoogle, oauthhotmail, nome, tipo, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('v1UsuarioPut', function() {
        it('should call v1UsuarioPut successfully', function(done) {
          // TODO: uncomment, update parameter values for v1UsuarioPut call
          /*
          var opts = {};

          instance.v1UsuarioPut(opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
    });
  });

}));
